name: semola
description: >-
  An hyphenation engine for the italian language. The engine is able to hyphenate 
  single words and can be easily configured with user-defined exceptions.
version: 0.0.6+4
homepage: https://github.com/slashdotted/semola-flutter

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  substitute: ^0.0.6

dev_dependencies:
  test: ^1.22.2
  flutter_lints: ^2.0.3